spring:
  config:
    name: configserver
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Pavel-Soloduha/spring-cloud-config-test-configs
          skipSslValidation: true
          refreshRate: 2
          force-pull: true
          cloneOnStart: true

server.port: 8888

